import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { ThemeProvider } from "@/app/_providers/ThemeProvider";
import QueryProvider from "@/app/_providers/QueryProvider";
import { ApiProvider } from "@/febe";
import NavBar from "@/app/_components/nav/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <QueryProvider>
            <ApiProvider>
              <div className="min-h-screen flex flex-col">
                <NavBar />
                <main className="flex-1">{children}</main>
              </div>
            </ApiProvider>
          </QueryProvider>
        </ThemeProvider>


        { /* <-- conditionally include the Piny script */ }
        {process.env.NODE_ENV === 'development' && process.env.PINY_VISUAL_SELECT === 'true' && (
        <Script
          src="/_piny/piny.phone.js"
          strategy="beforeInteractive" 
        />)} 
        { /* <-- conditionally include the Piny script */ }
      </body>
    </html>
  );
}
